### PR TITLE
Allow external links in Blog Postings

### PR DESCRIPTION
**Pull request by ahdezma**
This PR creates a new variable for `.md` files: `url`. If this variable is present, its value will be used to create an external url for a BlogPosting.

Also, make the whole card the link, instead of having a "Learn more" button.

### CODE REVIEW

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
Hey @ahdezma, why did you removed Learn More button? Could you explain more about it?

**Comment by ahdezma** [comment]
Hi @diegonvs I removed the button since it is not needed (the whole card is the link now)

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diegonvs** [comment]
Pull request submitted to https://github.com/diegonvs/gatsby-boilerplate/pull/75. [See changes here.](https://github.com/diegonvs/gatsby-boilerplate/compare/535bc1a~1...535bc1a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
